# Docker Compose for CNC Simulator
# Generates CNC machine sensor data and sends to external MQTT broker
version: '3.8'

services:
  cnc-simulator:
    build: .
    container_name: cnc-simulator
    environment:
      # Connect to external MQTT broker (UMH-Core, HiveMQ, etc.)
      - MQTT_BROKER_URL=mqtt://umh-core:1883
      - MQTT_USERNAME=
      - MQTT_PASSWORD=
      - PUBLISH_INTERVAL=3000
      - ENABLE_LOGGING=true
      - OUTPUT_FORMAT=umh
      - FACTORY_NAME=demo-factory
      - SITE_NAME=plant-1
    volumes:
      # Mount environment file if it exists for local overrides
      - ./.env:/app/.env:ro
    restart: unless-stopped
    # Connect to external network where UMH-Core or other MQTT broker runs
    networks:
      - default
    # Add labels for container management
    labels:
      - "com.cnc-simulator.service=data-generator"
      - "com.cnc-simulator.version=2.0"
      - "com.cnc-simulator.description=CNC Factory Sensor Data Generator"

# Use default network to connect to external services
networks:
  default:
    driver: bridge