version: '3.8'

services:
  # UMH Core - Main data processing platform
  umh-core:
    image: ghcr.io/united-manufacturing-hub/umh:latest
    container_name: umh-core
    ports:
      - "8090:8090"  # UMH API
      - "9092:9092"  # Kafka/Redpanda
      - "8091:8091"  # Benthos Topic Browser
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://umh-core:9092
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - UMH_LOG_LEVEL=INFO
      - POSTGRES_HOST=timescaledb
      - POSTGRES_PORT=5432
      - POSTGRES_DB=uns_production
      - POSTGRES_USER=uns_admin
      - POSTGRES_PASSWORD=uns_secure_password_2024
    volumes:
      - umh_data:/data
    networks:
      - umh_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # TimescaleDB for time-series data storage
  timescaledb:
    image: timescale/timescaledb:latest-pg16
    container_name: timescaledb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=uns_production
      - POSTGRES_USER=uns_admin
      - POSTGRES_PASSWORD=uns_secure_password_2024
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256
    volumes:
      - timescale_data:/var/lib/postgresql/data
      - ./scripts/init-timescale.sql:/docker-entrypoint-initdb.d/init-timescale.sql
    networks:
      - umh_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U uns_admin -d uns_production"]
      interval: 30s
      timeout: 10s
      retries: 3

  # CNC Machine Simulator with UMH Integration
  cnc-simulator:
    build:
      context: ./cnc-simulator-standalone
      dockerfile: Dockerfile.umh
    container_name: cnc-simulator-umh
    environment:
      - NODE_ENV=production
      - UMH_HOST=umh-core
      - UMH_PORT=8090
      - LOG_LEVEL=info
      - SIMULATION_INTERVAL=5000
      - MACHINES_COUNT=10
    networks:
      - umh_network
    restart: unless-stopped
    depends_on:
      umh-core:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "node", "-e", "console.log('CNC Simulator healthy')"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Portainer for container management
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - umh_network
    restart: unless-stopped

networks:
  umh_network:
    driver: bridge
    name: umh_network

volumes:
  umh_data:
    name: umh_data
  timescale_data:
    name: timescale_data
  portainer_data:
    name: portainer_data